[package]
name = "sourcerenderer_bsp"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
nalgebra = "0.26.2"
zip = { version = "0.5.11", default-features = false, default_features = false, features = ["deflate"] }
